### ISSUE TITLE
would it be possible to record "all" choices, not only the "final"

### ISSUE THREAD

**Issue by yarikoptic** [psychoinformatics-de/dmc#22]
I feel like some folks might go back and change answers to previous questions wherever they see/answer the next one.  It could happen for various reasons
- not clear to them original question
- missing "know" vs "use" difference
- next question serving them as a reminder of something (e.g. question about data papers  reminding them about additional dataset they collaborated on with someone etc)

knowing that might be useful and I guess might be easily captured if you capture each question responses entries as a separate object and just maintain the list of them with unique ids attached to each question so you could rebuild entire chronology or just get the last entry for each question.

**Comment by aqw** [comment]
I see your point, but there are some practicality issues with implementing it.

Closing. Reopen if you strongly object.

---Alex

**Comment by yarikoptic** [comment]
Any implementation of something new had issues, but it is all goes on scale with how difficult those are. Didn't look into the code yet - so how bad it would be if to implement?

**Comment by aqw** [comment]
> Any implementation of something new had issues, but it is all goes on scale with how difficult those are.

Of this I am well aware; I re-caulked my shower this weekend.

> Didn't look into the code yet - so how bad it would be if to implement?

It's less of a code issue and more of a practicality issue. For some users, the object storing the chronology will be huge (relative to the actual results). For example: keyboard users like you. Scrolling, through, every, damn, value. How about text fields as they're being entered?

But the biggest issue, IMO, is betraying user trust. Most users don't expect forms to save/submit data that's not in the final submission. What if someone accidentally pastes something from their clipboard? A password perhaps? If they don't want to share it, they wouldn't have removed it. Let's respect the status quo and user intent.

As I said before. If you strongly object, reopen. Otherwise, I'll work on other outstanding issues.

---Alex
